### ISSUE TITLE
Allow user to execute previous commands

### ISSUE THREAD

**Issue by karthiks2611** [PranavMurali/QWERTY#11]
If a command is too big, then he must be able to execute that previous command by pressing the up arrow, and pressing enter

![Screenshot from 2021-04-26 13-01-52](https://user-images.githubusercontent.com/73390717/116045560-c6c0f280-a68f-11eb-9c8d-1db19ccead2f.png)

**Comment by PranavMurali** [comment]
We were going to implement that in the next major release, forgot to add to our expected features list. Thanks for trying it out! @karthiks2611

**Comment by PranavMurali** [comment]
We were going to implement that in the next major release, forgot to add to our expected features list. Thanks for trying it out! @karthiks2611
